title: Last Asylum Guide
description: A strategy compendium for Last Asylum.
theme: null
url: "https://la-s78.github.io"
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
collections_dir: "collections"
collections:
  home:
    output: false
  rules:
    output: false
  guides:
    output: false
  guide_panes:
    output: false
  alliance:
    output: false
plugins:
  - jekyll-polyglot
languages: ["de", "en", "es", "fr", "ru", "tr", "uk"]
default_lang: "en"
exclude_from_localization:
  - images/
  - css/
  - js/