title: Last Asylum Guide
description: A strategy compendium for Last Asylum.
theme: null
url: "https://la-s78.github.io"
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - redirect.html
collections_dir: "collections"
collections:
  home:
    output: false
  rules:
    output: false
  guide_index:
    output: false
  guide_panes:
    output: false
    directory: "_guide_panes"
  alliance:
    output: false
languages: ["de", "en", "es", "fr", "ru", "tr", "uk", "it"]
default_lang: "en"
defaults:
  - scope:
      path: "guides"
    values:
      permalink: "/guides/:basename.html"
pwa:
  sw_src_filepath: sw.js
  sw_dest_filename: sw.js
  dest_js_directory: js
  precache_recent_posts_num: 0
  precache_glob_directory: /
  precache_glob_patterns:
    - "{css,js,images}/**/*.{css,js,png,jpg,jpeg,svg,webp}"
    - "**/*.html"
    - "site.webmanifest"