title: Last Asylum Guide
description: A strategy compendium for Last Asylum.
theme: null
url: "https://la-s78.github.io"
kramdown:
  input: GFM
  syntax_highlighter: rouge
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - redirect.html
  - vercel.json
  - _source/
collections_dir: "collections"
collections:
  home:
    output: false
  rules:
    output: false
  guide_index:
    output: false
  guide_panes:
    output: false
    directory: "_guide_panes"
  alliance:
    output: false
languages: ["de", "en", "es", "fr", "ru", "tr", "uk", "it"]
default_lang: "en"
defaults:
  - scope:
      path: "guides"
    values:
      permalink: "/guides/:basename.html"